# Generated by Django 4.1.7 on 2023-03-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvalapp', '0002_approvalrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approver',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requester',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
